services:
    mongodb1:
        image: arm64v8/mongo:6.0.23-jammy
        platform: linux/arm64/v8
        container_name: mongodb1
        command: --replSet myRepl --keyFile /keys/mongodb-keyfile
        ports:
            - "27017:27017"
        volumes:
            - ./dockers/data/mongodb1:/data/db
            - keys:/keys
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: 1234
            MONGO_INITDB_DATABASE: maple-story
        depends_on:
            - key-gen
        restart: always
        networks:
            - maplestory

    mongodb2:
        image: arm64v8/mongo:6.0.23-jammy
        platform: linux/arm64/v8
        container_name: mongodb2
        command: --replSet myRepl --keyFile /keys/mongodb-keyfile
        ports:
            - "27018:27017"
        volumes:
            - ./dockers/data/mongodb2:/data/db
            - keys:/keys
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: 1234
            MONGO_INITDB_DATABASE: maple-story
        depends_on:
            - key-gen
        restart: always
        networks:
            - maplestory

    mongodb3:
        image: arm64v8/mongo:6.0.23-jammy
        platform: linux/arm64/v8
        container_name: mongodb3
        command: --replSet myRepl --keyFile /keys/mongodb-keyfile
        ports:
            - "27019:27017"
        volumes:
            - ./dockers/data/mongodb3:/data/db
            - keys:/keys
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: 1234
            MONGO_INITDB_DATABASE: maple-story
        depends_on:
            - key-gen
        restart: always
        networks:
            - maplestory
    key-gen:
        build: ./dockers/mongodb-replica/key
        volumes:
            - keys:/keys
        restart: "no"

    init-replica:
        build: ./dockers/mongodb-replica/init
        depends_on:
            - mongodb1
            - mongodb2
            - mongodb3
        networks:
            - maplestory    
        restart: "no"

volumes:
    keys:

networks:
    maplestory:
        external: true
